{% set name = "trubar" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trubar-{{ version }}.tar.gz
  sha256: a46f7087561ac9528e20354a68b92ea7742db0aae2240b1e6acca5040ca6e9a6

build:
  entry_points:
    - trubar = trubar.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=40.9.0
    - wheel
    - pip
  run:
    - python >=3.9
    - libcst
    - pyyaml

test:
  imports:
    - trubar
  commands:
    - pip check
    - trubar --help
  requires:
    - pip

about:
  home: https://github.com/janezd/trubar
  summary: Utility for translation of Python sources
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janezd
